### ISSUE TITLE
Minor grammar error in testing doc

### ISSUE THREAD

**Issue by TonyCTurner** [middyjs/middy#1078]
**What does this implement/fix? Explain your changes.**
Minor grammar error in testing doc

**Does this close any currently open issues?**
No

**Any relevant logs, error output, etc?**
No

**Environment:**
 - Node.js: [e.g. 16]
 - Middy: [e.g. 3.0.0]
 - AWS SDK [e.g. 2.1000.0]

**Any other comments?**

**Todo List:**
- [ ] Feature/Fix fully implemented
- [ ] Added tests
  - [ ] Unit tests
  - [ ] Benchmark tests (if applicable)
- [ ] Updated relevant documentation
- [ ] Updated relevant examples
