### ISSUE TITLE
Version 5

### ISSUE THREAD

**Issue by willfarrell** [middyjs/middy#940]
aka "The ESM Only Update"

Alpha: May/June (after initial nodejs release)
Beta: Sept/Oct
Release: Nov (after nodejs active LTS starts)

* Timelines based on AWS nodejs20.x release cycle

## Planned
- [x] Drop Node v16, Add support fro Node v20 (https://github.com/aws/aws-lambda-base-images/issues/91)
  - [x] Update `engines` to `"node": ">=18"`
  - [x] Update github workflows `node-version`
  - [x] Update `swc` to use `es2022` (https://github.com/tsconfig/bases/tree/main/bases)
- [x] Drop CJS support, ESM only (do last, touch base with Powertools team before, they still use cjs)
- [x] TypeScript Update #1023
- [x] `event-normalizer`: review for any new events from [AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-services.html) and [event list](https://github.com/michaelbrewer/aws-lambda-events)
- [x] `http-security-headers`: review against helmet, MDN, ASVS
- [x] Update all custom error messages to follow same error pattern. {cause:{package:'@middy/*****', ...}}
- [x] `http-multipart-body-parser` change `disableContentTypeError` to `false` by default
- [x] `http-urlencoded-body-parser` change `disableContentTypeError` to `false` by default
- [x] `http-json-body-parser` change `disableContentTypeError` to `false` by default
- [x] `http-cors` change `disableBeforePreflightResponse` to `false` by default
- [x] `s3-object-response` update to use `fetch` over `https`
  - [ ] [X-Ray doesn't support `fetch`](https://github.com/aws/aws-xray-sdk-node/issues/531)
- [x] `ws-json-body-parser` deprecate `rawBody` from event
- [x] store `preferred*` in context instead of event for http-content-negotiation
- [x] `error-logger` pass in context with `request.error`

### >= 17
- [x] replace deep clone hack for `structuredClone`
  - [x] input-output-logger
- [x] Update how Abort timeout works in `core` (https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout) - No, prevent use to manual abort which is useful.

### >= 18
- [x] update to use `fetch` over `https`

## New Middleware?
- [x] kms - download public key(s) - Nah
- [x] stream - apply streams to key path - Nah
- [x] sfn-large payload #1066 - Nah

## Maybe
- [ ] benchmarking (can be done after release)
- [x] switch to esbuild? Nah, dropping CJS
- [ ] Move to Otel for Logs, Metrics, Traces? https://github.com/aws/aws-xray-sdk-node/issues/515 
  - Update Logs, Metrics, Traces to use OTel if ready (https://github.com/willfarrell/aws-wishlist#lambda)
  - Use Otel: https://aws-otel.github.io/docs/getting-started/javascript-sdk
  - Use powertools: https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/tracer/#patching-aws-sdk-clients
   - discussion: https://github.com/awslabs/aws-lambda-powertools-typescript/discussions/665
- [ ] `error-logger` update to print otel by default
- [ ] `input-output-logger` update to print in otel format
- [x] deprecate use of `qs` in `http-urlencode-body-parser` for `URLSearchParams`. No, doesn't support nested objects though

## Next Version
- [ ] Update abort signals if Lambda adds support
- [ ] Routers updated to support URLPattern? No, still experimental
- [x] `http-urlencode-body-parser` rename to `http-urlencoded-body-parser`? Nah

**Comment by KillDozerX2** [comment]
Either you're moving too fast to I'm too slow. I just switched to node16 today and saw this.
Anyways, keep up the good work guys!

**Comment by dave-irvine** [comment]
Can I 👎 on `Drop CJS support, ESM only`?.

I cannot describe the pain I have gone through trying to use `node-fetch` in ESM-only mode, I had to drop down to their previous major release. I cannot make ESM-only work with `esbuild` no matter what I try.

https://github.com/node-fetch/node-fetch/issues/1263 describes a litany of issues people are facing.

Just my 2 cents, I can understand wanting to move forward.

**Comment by willfarrell** [comment]
Thanks for the feedback. It's just an idea right now. FYI `fetch` is built into NodeJS 18, finally no more polyfill is needed.

This is the esbuild script I use, if you'd like to give it a try:
```
node_modules/.bin/esbuild ${1} \
		--platform=node --format=esm  --target=node18 --bundle --minify \
		--banner:js="import { createRequire } from 'module';const require = (m) => { if (m === './reserved.js') return {}; return createRequire(import.meta.url)(m);};const __dirname='.';" \
		--legal-comments=external --sourcemap=external \
		--allow-overwrite --outfile=${1%.js}.mjs
```

**Comment by olanb7** [comment]
Integration with `aws-lambda-powertools` would be a nice add. It's not much, but we're currently enriching the logger in middleware:

```
export const LoggerMiddleware = (logger: Logger): middy.MiddlewareObj => {

  const before: middy.MiddlewareFn = async (request: middy.Request): Promise<void> => {
    logger.addContext(request.context);
    logger.addPersistentLogAttributes({
      service: request.context.functionName,
      ...getIdentityAttributes(request),
    });
    
    ...
 ```

**Comment by willfarrell** [comment]
`5.0.0-rc.0` is now released.
